[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[functions."discover-venues"]
  timeout = 300

[functions."run-scraper"]  
  timeout = 300

[functions."update-venue-status"]
  timeout = 30

[functions."add-approved-venues"]
  timeout = 60